defaults:
  - ArbitraryReorient.yaml

name: ARv3

_target_: tasks.ihm.arv3.ArbitraryReorientv3

env:
  feedbackObs: [ "hand_joint_pos",  "hand_joint_target", "ftip_contact_bool", "desired_rot_axis", "desired_rot_angle" ]
  feedbackState: [ "hand_joint_pos",  "hand_joint_target", "ftip_contact_force", "object_state", "hand_joint_torque", "ftip_contact_pos", "desired_rot_axis", "desired_rot_angle"  ]

  # reward terms
  reward:
    angVelClipMax: 0.5
    angVelClipMin: -0.5
    rotationRewardScale: 1.0
    objectLinVelPenaltyScale: -0.3
    poseDiffPenaltyScale: -0.0 # leave as is, scripts will handle changing when necessary
    torquePenaltyScale: -0.0
    workPenaltyScale: 0.0
    ftip_obj_disp_pen: 0.0
    out_of_bounds_pen: 0.0