defaults:
  - /task/FingerGaiting
  - /actor/MLP
  - /critic/MLP
  - /planner/RRT
  - /actor_trainer/PPO
  - /critic_trainer/default

name: FingerGaitingPPO
_target_: rrl.rrl.RRL

task:
  env:
    envSpacing: 2.0


# Value and advantage estimation
normalize_input: True
normalize_value: True
value_bootstrap: True
normalize_advantage: True # not respected, essentially hardcoded to true in ExperienceReplay
gamma: 0.99
tau: 0.95


# Rollouts horizon
play_horizon_length: 8


# snapshot setting
save_best_after: 5
save_frequency: 500
max_agent_steps: 10_000_000_000
eval_frequency: 5
