_target_: algo.prm.PRM
#_target_: rrl.planner.rrf.RRF

rollout_len: 8
first_step: True
samples_per_epoch: 32
visualize_reset_states: False
visualize_rrt_tree: True
local_planner: policy
run_once: False
extract_optimal: False
num_reset_states: 100000

save_states: True
states_file_name: AR-v1-seed2.npy